[workspace]
members = ["contracts/*"]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false

[profile.release.package.yield-optimizer]
codegen-units = 1
incremental = false
